### ISSUE TITLE
Validate CUDA support. How easy it is to run tasks on GPU?

### ISSUE THREAD

**Issue by laugustyniak** [CLARIN-PL/embeddings#36]

**Comment by ktagowski** [comment]
Currently we are missing following functionality:

- [ ] We can't setup device e.g. in Multi-GPU env
- [ ] We can't setup flair embedding_store to GPU

**Comment by djaniak** [comment]
Flair uses GPU as a default if cuda is available. 
The device is defined in __init__.py file: https://github.com/flairNLP/flair/blob/master/flair/__init__.py and to change it you can simply assign new device to this variable: flair.device = torch.device("cuda:0")/torch.device("cpu") since flair framework builds directly on PyTorch. To best of my knowledge flair does not support the multi GPU yet. 

In our library we could either ask the user to change the device with flair or simply add a wrapper getter and setters to assign a new variable to flair.device under the hood, e.g.:

```
import clarin_embeddings as clarin_emb

clarin_emb.set_device(torch.device("cpu"))
print(clarin_emb.get_device())
```

**Comment by djaniak** [comment]
There is also embeddings_storage_mode argument (by default set to None) in predict method in flair.nn.Model class, e.g. SequenceTagger. If on a device we have cuda support it will be automatically set as a default device. If we set the flair.device to CPU, the embeddings storage mode will remain as GPU.

```
:param embedding_storage_mode: default is 'none' which is always best. Only set to 'cpu' or 'gpu' if you wish to not only predict, but also keep the generated embeddings in CPU or GPU memory respectively. 
'gpu' to store embeddings in GPU memory.
```
